[package]
name = "cryptopals-rs"
version = "0.1.0"
authors = ["Curran McConnell <curran@mercury.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
bytes = "1.0.1"
